behaviors:
  MoveToTarget:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      gail:
        gamma: 0.99
        strength: 0.5
        demo_path: Demos/MoveToTargetDemo.demo
    behavioral_cloning:
        demo_path: Demos/MoveToTargetDemo.demo
        strength: 0.5
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 100000